#ifndef SYSCALL32_H

#define __COMPAT_NR_restart_syscall 0
#define __COMPAT_NR_exit 1
#define __COMPAT_NR_fork 2
#define __COMPAT_NR_read 3
#define __COMPAT_NR_write 4
#define __COMPAT_NR_open 5
#define __COMPAT_NR_close 6
#define __COMPAT_NR_creat 8
#define __COMPAT_NR_link 9
#define __COMPAT_NR_unlink 10
#define __COMPAT_NR_execve 11
#define __COMPAT_NR_chdir 12
#define __COMPAT_NR_mknod 14
#define __COMPAT_NR_chmod 15
#define __COMPAT_NR_lchown 16
#define __COMPAT_NR_lseek 19
#define __COMPAT_NR_getpid 20
#define __COMPAT_NR_mount 21
#define __COMPAT_NR_setuid 23
#define __COMPAT_NR_getuid 24
#define __COMPAT_NR_ptrace 26
#define __COMPAT_NR_pause 29
#define __COMPAT_NR_access 33
#define __COMPAT_NR_nice 34
#define __COMPAT_NR_sync 36
#define __COMPAT_NR_kill 37
#define __COMPAT_NR_rename 38
#define __COMPAT_NR_mkdir 39
#define __COMPAT_NR_rmdir 40
#define __COMPAT_NR_dup 41
#define __COMPAT_NR_pipe 42
#define __COMPAT_NR_times 43
#define __COMPAT_NR_brk 45
#define __COMPAT_NR_setgid 46
#define __COMPAT_NR_getgid 47
#define __COMPAT_NR_geteuid 49
#define __COMPAT_NR_getegid 50
#define __COMPAT_NR_acct 51
#define __COMPAT_NR_umount2 52
#define __COMPAT_NR_ioctl 54
#define __COMPAT_NR_fcntl 55
#define __COMPAT_NR_setpgid 57
#define __COMPAT_NR_umask 60
#define __COMPAT_NR_chroot 61
#define __COMPAT_NR_ustat 62
#define __COMPAT_NR_dup2 63
#define __COMPAT_NR_getppid 64
#define __COMPAT_NR_getpgrp 65
#define __COMPAT_NR_setsid 66
#define __COMPAT_NR_sigaction 67
#define __COMPAT_NR_setreuid 70
#define __COMPAT_NR_setregid 71
#define __COMPAT_NR_sigsuspend 72
#define __COMPAT_NR_sigpending 73
#define __COMPAT_NR_sethostname 74
#define __COMPAT_NR_setrlimit 75
#define __COMPAT_NR_getrusage 77
#define __COMPAT_NR_gettimeofday 78
#define __COMPAT_NR_settimeofday 79
#define __COMPAT_NR_getgroups 80
#define __COMPAT_NR_setgroups 81
#define __COMPAT_NR_symlink 83
#define __COMPAT_NR_readlink 85
#define __COMPAT_NR_uselib 86
#define __COMPAT_NR_swapon 87
#define __COMPAT_NR_reboot 88
#define __COMPAT_NR_munmap 91
#define __COMPAT_NR_truncate 92
#define __COMPAT_NR_ftruncate 93
#define __COMPAT_NR_fchmod 94
#define __COMPAT_NR_fchown 95
#define __COMPAT_NR_getpriority 96
#define __COMPAT_NR_setpriority 97
#define __COMPAT_NR_statfs 99
#define __COMPAT_NR_fstatfs 100
#define __COMPAT_NR_syslog 103
#define __COMPAT_NR_setitimer 104
#define __COMPAT_NR_getitimer 105
#define __COMPAT_NR_stat 106
#define __COMPAT_NR_lstat 107
#define __COMPAT_NR_fstat 108
#define __COMPAT_NR_vhangup 111
#define __COMPAT_NR_wait4 114
#define __COMPAT_NR_swapoff 115
#define __COMPAT_NR_sysinfo 116
#define __COMPAT_NR_fsync 118
#define __COMPAT_NR_sigreturn 119
#define __COMPAT_NR_clone 120
#define __COMPAT_NR_setdomainname 121
#define __COMPAT_NR_uname 122
#define __COMPAT_NR_adjtimex 124
#define __COMPAT_NR_mprotect 125
#define __COMPAT_NR_sigprocmask 126
#define __COMPAT_NR_init_module 128
#define __COMPAT_NR_delete_module 129
#define __COMPAT_NR_quotactl 131
#define __COMPAT_NR_getpgid 132
#define __COMPAT_NR_fchdir 133
#define __COMPAT_NR_bdflush 134
#define __COMPAT_NR_sysfs 135
#define __COMPAT_NR_personality 136
#define __COMPAT_NR_setfsuid 138
#define __COMPAT_NR_setfsgid 139
#define __COMPAT_NR__llseek 140
#define __COMPAT_NR_getdents 141
#define __COMPAT_NR__newselect 142
#define __COMPAT_NR_flock 143
#define __COMPAT_NR_msync 144
#define __COMPAT_NR_readv 145
#define __COMPAT_NR_writev 146
#define __COMPAT_NR_getsid 147
#define __COMPAT_NR_fdatasync 148
#define __COMPAT_NR__sysctl 149
#define __COMPAT_NR_mlock 150
#define __COMPAT_NR_munlock 151
#define __COMPAT_NR_mlockall 152
#define __COMPAT_NR_munlockall 153
#define __COMPAT_NR_sched_setparam 154
#define __COMPAT_NR_sched_getparam 155
#define __COMPAT_NR_sched_setscheduler 156
#define __COMPAT_NR_sched_getscheduler 157
#define __COMPAT_NR_sched_yield 158
#define __COMPAT_NR_sched_get_priority_max 159
#define __COMPAT_NR_sched_get_priority_min 160
#define __COMPAT_NR_sched_rr_get_interval 161
#define __COMPAT_NR_nanosleep 162
#define __COMPAT_NR_mremap 163
#define __COMPAT_NR_setresuid 164
#define __COMPAT_NR_getresuid 165
#define __COMPAT_NR_poll 168
#define __COMPAT_NR_nfsservctl 169
#define __COMPAT_NR_setresgid 170
#define __COMPAT_NR_getresgid 171
#define __COMPAT_NR_prctl 172
#define __COMPAT_NR_rt_sigreturn 173
#define __COMPAT_NR_rt_sigaction 174
#define __COMPAT_NR_rt_sigprocmask 175
#define __COMPAT_NR_rt_sigpending 176
#define __COMPAT_NR_rt_sigtimedwait 177
#define __COMPAT_NR_rt_sigqueueinfo 178
#define __COMPAT_NR_rt_sigsuspend 179
#define __COMPAT_NR_pread64 180
#define __COMPAT_NR_pwrite64 181
#define __COMPAT_NR_chown 182
#define __COMPAT_NR_getcwd 183
#define __COMPAT_NR_capget 184
#define __COMPAT_NR_capset 185
#define __COMPAT_NR_sigaltstack 186
#define __COMPAT_NR_sendfile 187
#define __COMPAT_NR_vfork 190
#define __COMPAT_NR_ugetrlimit 191	/* SuS compliant getrlimit */
#define __COMPAT_NR_mmap2 192
#define __COMPAT_NR_truncate64 193
#define __COMPAT_NR_ftruncate64 194
#define __COMPAT_NR_stat64 195
#define __COMPAT_NR_lstat64 196
#define __COMPAT_NR_fstat64 197
#define __COMPAT_NR_lchown32 198
#define __COMPAT_NR_getuid32 199
#define __COMPAT_NR_getgid32 200
#define __COMPAT_NR_geteuid32 201
#define __COMPAT_NR_getegid32 202
#define __COMPAT_NR_setreuid32 203
#define __COMPAT_NR_setregid32 204
#define __COMPAT_NR_getgroups32 205
#define __COMPAT_NR_setgroups32 206
#define __COMPAT_NR_fchown32 207
#define __COMPAT_NR_setresuid32 208
#define __COMPAT_NR_getresuid32 209
#define __COMPAT_NR_setresgid32 210
#define __COMPAT_NR_getresgid32 211
#define __COMPAT_NR_chown32 212
#define __COMPAT_NR_setuid32 213
#define __COMPAT_NR_setgid32 214
#define __COMPAT_NR_setfsuid32 215
#define __COMPAT_NR_setfsgid32 216
#define __COMPAT_NR_getdents64 217
#define __COMPAT_NR_pivot_root 218
#define __COMPAT_NR_mincore 219
#define __COMPAT_NR_madvise 220
#define __COMPAT_NR_fcntl64 221
#define __COMPAT_NR_gettid 224
#define __COMPAT_NR_readahead 225
#define __COMPAT_NR_setxattr 226
#define __COMPAT_NR_lsetxattr 227
#define __COMPAT_NR_fsetxattr 228
#define __COMPAT_NR_getxattr 229
#define __COMPAT_NR_lgetxattr 230
#define __COMPAT_NR_fgetxattr 231
#define __COMPAT_NR_listxattr 232
#define __COMPAT_NR_llistxattr 233
#define __COMPAT_NR_flistxattr 234
#define __COMPAT_NR_removexattr 235
#define __COMPAT_NR_lremovexattr 236
#define __COMPAT_NR_fremovexattr 237
#define __COMPAT_NR_tkill 238
#define __COMPAT_NR_sendfile64 239
#define __COMPAT_NR_futex 240
#define __COMPAT_NR_sched_setaffinity 241
#define __COMPAT_NR_sched_getaffinity 242
#define __COMPAT_NR_io_setup 243
#define __COMPAT_NR_io_destroy 244
#define __COMPAT_NR_io_getevents 245
#define __COMPAT_NR_io_submit 246
#define __COMPAT_NR_io_cancel 247
#define __COMPAT_NR_exit_group 248
#define __COMPAT_NR_lookup_dcookie 249
#define __COMPAT_NR_epoll_create 250
#define __COMPAT_NR_epoll_ctl 251
#define __COMPAT_NR_epoll_wait 252
#define __COMPAT_NR_remap_file_pages 253
#define __COMPAT_NR_set_tid_address 256
#define __COMPAT_NR_timer_create 257
#define __COMPAT_NR_timer_settime 258
#define __COMPAT_NR_timer_gettime 259
#define __COMPAT_NR_timer_getoverrun 260
#define __COMPAT_NR_timer_delete 261
#define __COMPAT_NR_clock_settime 262
#define __COMPAT_NR_clock_gettime 263
#define __COMPAT_NR_clock_getres 264
#define __COMPAT_NR_clock_nanosleep 265
#define __COMPAT_NR_statfs64 266
#define __COMPAT_NR_fstatfs64 267
#define __COMPAT_NR_tgkill 268
#define __COMPAT_NR_utimes 269
#define __COMPAT_NR_arm_fadvise64_64 270
#define __COMPAT_NR_pciconfig_iobase 271
#define __COMPAT_NR_pciconfig_read 272
#define __COMPAT_NR_pciconfig_write 273
#define __COMPAT_NR_mq_open 274
#define __COMPAT_NR_mq_unlink 275
#define __COMPAT_NR_mq_timedsend 276
#define __COMPAT_NR_mq_timedreceive 277
#define __COMPAT_NR_mq_notify 278
#define __COMPAT_NR_mq_getsetattr 279
#define __COMPAT_NR_waitid 280
#define __COMPAT_NR_socket 281
#define __COMPAT_NR_bind 282
#define __COMPAT_NR_connect 283
#define __COMPAT_NR_listen 284
#define __COMPAT_NR_accept 285
#define __COMPAT_NR_getsockname 286
#define __COMPAT_NR_getpeername 287
#define __COMPAT_NR_socketpair 288
#define __COMPAT_NR_send 289
#define __COMPAT_NR_sendto 290
#define __COMPAT_NR_recv 291
#define __COMPAT_NR_recvfrom 292
#define __COMPAT_NR_shutdown 293
#define __COMPAT_NR_setsockopt 294
#define __COMPAT_NR_getsockopt 295
#define __COMPAT_NR_sendmsg 296
#define __COMPAT_NR_recvmsg 297
#define __COMPAT_NR_semop 298
#define __COMPAT_NR_semget 299
#define __COMPAT_NR_semctl 300
#define __COMPAT_NR_msgsnd 301
#define __COMPAT_NR_msgrcv 302
#define __COMPAT_NR_msgget 303
#define __COMPAT_NR_msgctl 304
#define __COMPAT_NR_shmat 305
#define __COMPAT_NR_shmdt 306
#define __COMPAT_NR_shmget 307
#define __COMPAT_NR_shmctl 308
#define __COMPAT_NR_add_key 309
#define __COMPAT_NR_request_key 310
#define __COMPAT_NR_keyctl 311
#define __COMPAT_NR_semtimedop 312
#define __COMPAT_NR_vserver 313
#define __COMPAT_NR_ioprio_set 314
#define __COMPAT_NR_ioprio_get 315
#define __COMPAT_NR_inotify_init 316
#define __COMPAT_NR_inotify_add_watch 317
#define __COMPAT_NR_inotify_rm_watch 318
#define __COMPAT_NR_mbind 319
#define __COMPAT_NR_get_mempolicy 320
#define __COMPAT_NR_set_mempolicy 321
#define __COMPAT_NR_openat 322
#define __COMPAT_NR_mkdirat 323
#define __COMPAT_NR_mknodat 324
#define __COMPAT_NR_fchownat 325
#define __COMPAT_NR_futimesat 326
#define __COMPAT_NR_fstatat64 327
#define __COMPAT_NR_unlinkat 328
#define __COMPAT_NR_renameat 329
#define __COMPAT_NR_linkat 330
#define __COMPAT_NR_symlinkat 331
#define __COMPAT_NR_readlinkat 332
#define __COMPAT_NR_fchmodat 333
#define __COMPAT_NR_faccessat 334
#define __COMPAT_NR_pselect6 335
#define __COMPAT_NR_ppoll 336
#define __COMPAT_NR_unshare 337
#define __COMPAT_NR_set_robust_list 338
#define __COMPAT_NR_get_robust_list 339
#define __COMPAT_NR_splice 340
#define __COMPAT_NR_sync_file_range2 341
#define __COMPAT_NR_tee 342
#define __COMPAT_NR_vmsplice 343
#define __COMPAT_NR_move_pages 344
#define __COMPAT_NR_getcpu 345
#define __COMPAT_NR_epoll_pwait 346
#define __COMPAT_NR_kexec_load 347
#define __COMPAT_NR_utimensat 348
#define __COMPAT_NR_signalfd 349
#define __COMPAT_NR_timerfd_create 350
#define __COMPAT_NR_eventfd 351
#define __COMPAT_NR_fallocate 352
#define __COMPAT_NR_timerfd_settime 353
#define __COMPAT_NR_timerfd_gettime 354
#define __COMPAT_NR_signalfd4 355
#define __COMPAT_NR_eventfd2 356
#define __COMPAT_NR_epoll_create1 357
#define __COMPAT_NR_dup3 358
#define __COMPAT_NR_pipe2 359
#define __COMPAT_NR_inotify_init1 360
#define __COMPAT_NR_preadv 361
#define __COMPAT_NR_pwritev 362
#define __COMPAT_NR_rt_tgsigqueueinfo 363
#define __COMPAT_NR_perf_event_open 364
#define __COMPAT_NR_recvmmsg 365
#define __COMPAT_NR_accept4 366
#define __COMPAT_NR_fanotify_init 367
#define __COMPAT_NR_fanotify_mark 368
#define __COMPAT_NR_prlimit64 369
#define __COMPAT_NR_name_to_handle_at 370
#define __COMPAT_NR_open_by_handle_at 371
#define __COMPAT_NR_clock_adjtime 372
#define __COMPAT_NR_syncfs 373
#define __COMPAT_NR_sendmmsg 374
#define __COMPAT_NR_setns 375
#define __COMPAT_NR_process_vm_readv 376
#define __COMPAT_NR_process_vm_writev 377
#define __COMPAT_NR_kcmp 378
#define __COMPAT_NR_finit_module 379
#define __COMPAT_NR_sched_setattr 380
#define __COMPAT_NR_sched_getattr 381
#define __COMPAT_NR_renameat2 382
#define __COMPAT_NR_seccomp 383

#define SYSCALL32_H
#endif
